INSERT INTO [dbo].[Pizzas] ([Nombre], [Precio], [Cantidad]) VALUES (N'Margarita', CAST(7.1500 AS Money), 10)
INSERT INTO [dbo].[Pizzas] ([Nombre], [Precio], [Cantidad]) VALUES (N'Kebab', CAST(8.5000 AS Money), 7)
INSERT INTO [dbo].[Pizzas] ([Nombre], [Precio], [Cantidad]) VALUES (N'Carbonara', CAST(7.5000 AS Money), 8)
INSERT INTO [dbo].[Pizzas] ([Nombre], [Precio], [Cantidad]) VALUES (N'Romana', CAST(8.0000 AS Money), 7)
INSERT INTO [dbo].[Pizzas] ([Nombre], [Precio], [Cantidad]) VALUES (N'Barbacoa', CAST(8.5000 AS Money), 5)
INSERT INTO [dbo].[Pizzas] ([Nombre], [Precio], [Cantidad]) VALUES (N'Española', CAST(6.3500 AS Money), 6)
INSERT INTO [dbo].[Pizzas] ([Nombre], [Precio], [Cantidad]) VALUES (N'Pecado carnal', CAST(9.0000 AS Money), 5)
INSERT INTO [dbo].[Pizzas] ([Nombre], [Precio], [Cantidad]) VALUES (N'Hawaina', CAST(7.5000 AS Money), 3)
INSERT INTO [dbo].[Pizzas] ([Nombre], [Precio], [Cantidad]) VALUES (N'Marinera', CAST(8.5000 AS Money), 5)
INSERT INTO [dbo].[Pizzas] ([Nombre], [Precio], [Cantidad]) VALUES (N'Napolitana', CAST(9.0000 AS Money), 7)
INSERT INTO [dbo].[Pizzas] ([Nombre], [Precio], [Cantidad]) VALUES (N'Vegetariana', CAST(8.3500 AS Money), 6)
INSERT INTO [dbo].[Pizzas] ([Nombre], [Precio], [Cantidad]) VALUES (N'Otoñal', CAST(8.1500 AS Money), 4)
INSERT INTO [dbo].[Pizzas] ([Nombre], [Precio], [Cantidad]) VALUES (N'Berenjenal', CAST(7.5000 AS Money), 5)