INSERT INTO [dbo].[Especias] ([Nombre], [Precio], [Cantidad]) VALUES (N'Ajo', CAST(0.2500 AS Money), 50)
INSERT INTO [dbo].[Especias] ([Nombre], [Precio], [Cantidad]) VALUES (N'Albahaca', CAST(0.3000 AS Money), 60)
INSERT INTO [dbo].[Especias] ([Nombre], [Precio], [Cantidad]) VALUES (N'Azafrán', CAST(0.5000 AS Money), 65)
INSERT INTO [dbo].[Especias] ([Nombre], [Precio], [Cantidad]) VALUES (N'Orégano', CAST(0.1500 AS Money), 50)
INSERT INTO [dbo].[Especias] ([Nombre], [Precio], [Cantidad]) VALUES (N'Perejil', CAST(0.2000 AS Money), 60)
INSERT INTO [dbo].[Especias] ([Nombre], [Precio], [Cantidad]) VALUES (N'Pimentón', CAST(0.3000 AS Money), 55)
INSERT INTO [dbo].[Especias] ([Nombre], [Precio], [Cantidad]) VALUES (N'Sal', CAST(0.1000 AS Money), 80)
INSERT INTO [dbo].[Especias] ([Nombre], [Precio], [Cantidad]) VALUES (N'Tomillo', CAST(0.2000 AS Money), 75)
INSERT INTO [dbo].[Especias] ([Nombre], [Precio], [Cantidad]) VALUES (N'Pimienta negra', CAST(0.4000 AS Money), 80)