INSERT INTO [dbo].[Ingredientes] ([Nombre], [Precio], [Cantidad]) VALUES (N'Jamon York', CAST(0.5500 AS Money), 80)
INSERT INTO [dbo].[Ingredientes] ([Nombre], [Precio], [Cantidad]) VALUES (N'Jamon', CAST(1.2000 AS Money), 50)
INSERT INTO [dbo].[Ingredientes] ([Nombre], [Precio], [Cantidad]) VALUES (N'Bacon', CAST(0.8500 AS Money), 60)
INSERT INTO [dbo].[Ingredientes] ([Nombre], [Precio], [Cantidad]) VALUES (N'Queso', CAST(0.3500 AS Money), 55)
INSERT INTO [dbo].[Ingredientes] ([Nombre], [Precio], [Cantidad]) VALUES (N'Setas', CAST(1.0000 AS Money), 40)
INSERT INTO [dbo].[Ingredientes] ([Nombre], [Precio], [Cantidad]) VALUES (N'Pepperoni', CAST(1.3000 AS Money), 33)
INSERT INTO [dbo].[Ingredientes] ([Nombre], [Precio], [Cantidad]) VALUES (N'Chorizo', CAST(1.4000 AS Money), 30)
INSERT INTO [dbo].[Ingredientes] ([Nombre], [Precio], [Cantidad]) VALUES (N'Piña', CAST(2.0000 AS Money), 20)
INSERT INTO [dbo].[Ingredientes] ([Nombre], [Precio], [Cantidad]) VALUES (N'Berenjena', CAST(1.1500 AS Money), 32)
INSERT INTO [dbo].[Ingredientes] ([Nombre], [Precio], [Cantidad]) VALUES (N'Calabacin', CAST(1.2000 AS Money), 43)
INSERT INTO [dbo].[Ingredientes] ([Nombre], [Precio], [Cantidad]) VALUES (N'Alcachofa', CAST(1.0500 AS Money), 40)
INSERT INTO [dbo].[Ingredientes] ([Nombre], [Precio], [Cantidad]) VALUES (N'Tomate cherry', CAST(1.5000 AS Money), 35)
INSERT INTO [dbo].[Ingredientes] ([Nombre], [Precio], [Cantidad]) VALUES (N'Aceitunas negras', CAST(0.6000 AS Money), 100)
INSERT INTO [dbo].[Ingredientes] ([Nombre], [Precio], [Cantidad]) VALUES (N'Pollo', CAST(1.1000 AS Money), 50)
INSERT INTO [dbo].[Ingredientes] ([Nombre], [Precio], [Cantidad]) VALUES (N'Ternera', CAST(1.2000 AS Money), 40)
INSERT INTO [dbo].[Ingredientes] ([Nombre], [Precio], [Cantidad]) VALUES (N'Anchoas', CAST(0.8000 AS Money), 30)
INSERT INTO [dbo].[Ingredientes] ([Nombre], [Precio], [Cantidad]) VALUES (N'Cebolla', CAST(1.1000 AS Money), 33)
INSERT INTO [dbo].[Ingredientes] ([Nombre], [Precio], [Cantidad]) VALUES (N'Atun', CAST(1.2000 AS Money), 50)
INSERT INTO [dbo].[Ingredientes] ([Nombre], [Precio], [Cantidad]) VALUES (N'Salchichas', CAST(1.0000 AS Money), 60)
INSERT INTO [dbo].[Ingredientes] ([Nombre], [Precio], [Cantidad]) VALUES (N'Pimiento rojo', CAST(1.1000 AS Money), 50)
INSERT INTO [dbo].[Ingredientes] ([Nombre], [Precio], [Cantidad]) VALUES (N'Pimiento verde', CAST(1.1000 AS Money), 45)
