INSERT INTO [dbo].[Usuarios] ([Usuario], [Nombre], [Apellidos], [Contrasena], [Es_admin]) VALUES (N'adsf', N'asd', N'Osama', N'1234', 0)
INSERT INTO [dbo].[Usuarios] ([Usuario], [Nombre], [Apellidos], [Contrasena], [Es_admin]) VALUES (N'Osama', N'Osama', N'Alsaid', N'1234', 1)
INSERT INTO [dbo].[Usuarios] ([Usuario], [Nombre], [Apellidos], [Contrasena], [Es_admin]) VALUES (N'Alvaro', N'Juarez', N'Garcia', N'1234', 1)
INSERT INTO [dbo].[Usuarios] ([Usuario], [Nombre], [Apellidos], [Contrasena], [Es_admin]) VALUES (N'machinga', N'Mario', N'Sánchez', N'1234', 1)
INSERT INTO [dbo].[Usuarios] ([Usuario], [Nombre], [Apellidos], [Contrasena], [Es_admin]) VALUES (N'cliente1', N'Cliente', N'Cliente', N'1234', 0)